name: Build Comfy

on:
  workflow_dispatch:
  push:
    branches:
      - f2x-sound-test

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build ComfyVersion first
        run: msbuild ComfyVersion\ComfyVersion.vcxproj /p:Configuration=Release /p:Platform=x64 /p:SolutionDir="${{ github.workspace }}\"

      - name: Build ComfyData first
        run: msbuild ComfyData\ComfyDataBuild.vcxproj /p:Configuration=Release /p:Platform=x64 /p:SolutionDir="${{ github.workspace }}\"

      - name: Create ComfyData output folder
        run: New-Item -ItemType Directory -Force -Path ComfyData\data

      - name: Build solution
        run: msbuild Comfy.sln /p:Configuration=Release /p:Platform=x64 /m

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: Comfy-Release-x64
          path: |
            **/bin/x64-Release/*.exe
            **/bin/x64-Release/*.dll
            **/data/*.dat
